# Generated by Django 2.1.1 on 2018-11-24 12:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate_personal_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=60)),
                ('candidate_email', models.CharField(default='', max_length=60)),
                ('candidate_age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Job_application_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(blank=True, max_length=60, null=True)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('score_answer_relevance', models.FloatField(blank=True, null=True)),
                ('score_grammar_analysis', models.FloatField(blank=True, null=True)),
                ('score_sentiment_analysis', models.FloatField(blank=True, null=True)),
                ('candidate', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='candidate.Candidate_personal_details')),
                ('job', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='company.Job_details')),
            ],
        ),
    ]
