# Generated by Django 2.1.1 on 2018-10-20 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate_personal_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=60)),
                ('candidate_email', models.CharField(max_length=60)),
                ('candidate_id', models.IntegerField()),
                ('candidate_age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Job_application_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=60)),
                ('job_location', models.CharField(max_length=60)),
                ('job_position', models.CharField(max_length=60)),
                ('candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidate.Candidate_personal_details')),
            ],
        ),
    ]
