# Generated by Django 2.1.1 on 2018-10-20 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_application_details',
            old_name='candidate_id',
            new_name='candidate_id_foreign',
        ),
    ]
