# Generated by Django 2.1.1 on 2018-10-23 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20181023_1521'),
        ('candidate', '0002_auto_20181020_1309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate_personal_details',
            name='candidate_id',
        ),
        migrations.RemoveField(
            model_name='job_application_details',
            name='candidate_id_foreign',
        ),
        migrations.RemoveField(
            model_name='job_application_details',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='job_application_details',
            name='job_location',
        ),
        migrations.RemoveField(
            model_name='job_application_details',
            name='job_position',
        ),
        migrations.AddField(
            model_name='job_application_details',
            name='candidate_id_Foreign',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='candidate.Candidate_personal_details'),
        ),
        migrations.AddField(
            model_name='job_application_details',
            name='job_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='company.Job_details'),
        ),
        migrations.AlterField(
            model_name='candidate_personal_details',
            name='candidate_email',
            field=models.CharField(default='', max_length=60),
        ),
    ]
