# Generated by Django 2.1.1 on 2018-11-29 13:02

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0003_emotion_output'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion_output',
            name='emo_output',
            field=django.contrib.postgres.fields.hstore.HStoreField(),
        ),
    ]
