# Generated by Django 2.1.1 on 2018-11-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0004_job_application_details_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job_application_details',
            name='score_answer_relevance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_application_details',
            name='score_grammar_analysis',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job_application_details',
            name='score_sentiment_analysis',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
