# Generated by Django 2.1.1 on 2018-11-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0005_auto_20181104_1653'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_application_details',
            old_name='candidate_id_Foreign',
            new_name='candidate',
        ),
        migrations.RenameField(
            model_name='job_application_details',
            old_name='job_id',
            new_name='job',
        ),
        migrations.AddField(
            model_name='job_application_details',
            name='company_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
