# Generated by Django 2.1.1 on 2018-11-05 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_auto_20181104_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_application_details',
            old_name='job',
            new_name='job_id',
        ),
    ]
