# Generated by Django 2.1.1 on 2018-11-29 13:15

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0006_auto_20181129_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotion_output',
            name='emo_output',
            field=jsonfield.fields.JSONField(),
        ),
    ]
