# Generated by Django 2.1.1 on 2018-12-03 19:55

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('candidate', '0007_auto_20181129_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentiment_output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name_sentiment', models.CharField(max_length=200)),
                ('sentiment_score', jsonfield.fields.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Similarity_output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name_similarity', models.CharField(max_length=200)),
                ('similarity_score', models.CharField(max_length=200)),
            ],
        ),
    ]
