# Generated by Django 2.1.1 on 2018-11-05 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20181027_1532'),
        ('candidate', '0007_auto_20181105_1047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_application_details',
            name='job_id',
        ),
        migrations.AddField(
            model_name='job_application_details',
            name='job',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='company.Job_details'),
        ),
    ]
