# Generated by Django 2.1.1 on 2018-10-21 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=60)),
                ('company_email', models.CharField(max_length=60)),
                ('company_id', models.IntegerField()),
                ('company_phn', models.CharField(max_length=10)),
                ('company_city', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Job_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.IntegerField()),
                ('job_name', models.CharField(max_length=60)),
                ('job_location', models.CharField(max_length=60)),
                ('job_position', models.CharField(max_length=60)),
                ('company_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='company.Company_details')),
            ],
        ),
        migrations.CreateModel(
            name='Question_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_name', models.CharField(max_length=60)),
                ('question_model_answer', models.CharField(max_length=100)),
                ('question_id', models.IntegerField()),
                ('question_type', models.CharField(max_length=60)),
                ('job_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='company.Job_details')),
            ],
        ),
    ]
