# Generated by Django 2.1.1 on 2018-10-23 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_details',
            old_name='company_details',
            new_name='company',
        ),
        migrations.RemoveField(
            model_name='company_details',
            name='company_id',
        ),
        migrations.RemoveField(
            model_name='job_details',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='question_details',
            name='question_id',
        ),
    ]
