# Generated by Django 2.1.1 on 2018-10-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20181023_1521'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question_details',
            old_name='job_details',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='question_details',
            old_name='question_model_answer',
            new_name='model_answer',
        ),
        migrations.AddField(
            model_name='question_details',
            name='time_limit',
            field=models.IntegerField(default=3),
        ),
    ]
