# Generated by Django 2.1.1 on 2018-10-24 21:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0003_auto_20181023_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company_details',
            name='company_city',
        ),
        migrations.RemoveField(
            model_name='company_details',
            name='company_phn',
        ),
        migrations.AddField(
            model_name='company_details',
            name='company_location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='company_details',
            name='user',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company_details',
            name='company_name',
            field=models.TextField(max_length=500),
        ),
    ]
