# Generated by Django 2.0.1 on 2018-10-25 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20181024_2113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job_details',
            name='company',
        ),
        migrations.AddField(
            model_name='job_details',
            name='compId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='compId', to='company.Company_details'),
            preserve_default=False,
        ),
    ]
