# Generated by Django 2.1.1 on 2018-10-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_auto_20181024_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_details',
            name='model_answer',
            field=models.CharField(max_length=500),
        ),
    ]
