# Generated by Django 2.1.1 on 2018-10-27 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_auto_20181027_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='company_name',
            field=models.TextField(max_length=60),
        ),
        migrations.AlterField(
            model_name='question_details',
            name='model_answer',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='question_details',
            name='question_name',
            field=models.CharField(max_length=100),
        ),
    ]
