# Generated by Django 2.1.1 on 2018-10-29 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_auto_20181026_0142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company_details',
            name='company_name',
            field=models.TextField(max_length=50),
        ),
    ]
